# .github/workflows/my_flutter_package.yaml
name: Dart CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.2
      min_coverage: 50
      coverage_excludes: "*.g.dart"
