# .github/workflows/my_flutter_package.yaml
name: Dart CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
